apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopping-cart-db-pv-claim
  labels:
    app: shopping-cart-db 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shopping-cart-db-pv-volume
  labels:
    type: local
    app: shopping-cart-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"