apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
spec:
  selector:
    app: shopping-cart-service
  ports:
    - protocol: TCP
      port: 5000 
      name: shopping-cart-service 
  type: LoadBalancer